#
# Makefile for examples
#

.PHONY: all clean

all:
	@$(MAKE) -C benchmark all
	@$(MAKE) -C hello all
	@$(MAKE) -C mnist all

clean:
	@$(MAKE) -C benchmark clean
	@$(MAKE) -C hello clean
	@$(MAKE) -C mnist clean
